"""add instructions to exercises

Revision ID: 963747e71b6d
Revises: 00d27cef4ce4
Create Date: 2026-06-05 16:44:56.390505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '963747e71b6d'
down_revision: Union[str, Sequence[str], None] = '00d27cef4ce4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('instructions', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'instructions')
    # ### end Alembic commands ###
